#!/bin/bash

# check python installed
which python &> /dev/null
if [ "$?" != "0" ]; then
    echo "python is not installed..."
    exit 1
fi

# check pip installed
which pip &> /dev/null
if [ "$?" != "0" ]; then
    echo "pip (python package management system) is not installed..."
    exit 1
fi

# check tmux installed
which tmux &> /dev/null
if [ "$?" != "0" ]; then
    echo "tmux is not installed..."
    exit 1
fi

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

if [ ! -d $DIR/venv ]; then

	echo "- install Gazua~~~!!!"
	echo "- install path: $DIR"
fi

check_libs="$(pip freeze | grep urwid)"

if [ -z $check_libs ]; then
	pip install --user -r requirements.txt
fi


python $DIR/gazua.py
